"""add mode_name to chat_messages

Revision ID: a10c25103f18
Revises: ed1f3b9857aa
Create Date: 2026-08-03 20:36:55.794341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10c25103f18'
down_revision: Union[str, Sequence[str], None] = 'ed1f3b9857aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('mode_name', sa.String(), server_default="mode_chat", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'mode_name')
    # ### end Alembic commands ###
