"""move mode_name to chat_messages

Revision ID: c8023b756315
Revises: a10c25103f18
Create Date: 2026-08-03 21:27:58.537034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8023b756315'
down_revision: Union[str, Sequence[str], None] = 'a10c25103f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add the column to chat_messages but allow NULL values initially
    op.add_column('chat_messages', sa.Column('mode_name', sa.String(), nullable=True))
    
    # 2. Update existing rows with a default value (e.g., 'mode_chat')
    op.execute("UPDATE chat_messages SET mode_name = 'mode_chat' WHERE mode_name IS NULL")
    
    # 3. Alter the column to enforce NOT NULL
    op.alter_column('chat_messages', 'mode_name', nullable=False)
    
    # 4. Drop the old column from chat_sessions
    op.drop_column('chat_sessions', 'mode_name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('mode_name', sa.VARCHAR(), server_default=sa.text("'mode_chat'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('chat_messages', 'mode_name')
    # ### end Alembic commands ###